/*
===============================================================================
Magnitude
===============================================================================
Purpose:
    - See how performance differs by dimensions.
	
SQL Functions Used:
    - SUM()
    - COUNT()
    - GROUP BY , ORDER BY
===============================================================================
*/

-- Total products per category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- Number of units sold per product category
SELECT
    p.category,
    SUM(quantity) AS units_sold
FROM gold.fact_sales s
INNER JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY category
ORDER BY units_sold DESC;

-- Total profit generated by each product

SELECT
    p.category,
    p.subcategory,
    p.product_name,
    SUM(sales_amount) AS total_sale
FROM gold.fact_sales s
INNER JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY category, subcategory, product_name
ORDER BY total_sale DESC;

-- Total customer by gender 
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- How many times each customer made a purchase

SELECT  
    c.first_name, 
    c.last_name,
    COUNT(c.customer_key) AS customer_purchase
FROM gold.dim_customers c
INNER JOIN gold.fact_sales s
ON c.customer_key = s.customer_key
GROUP BY c.customer_key, first_name, last_name
ORDER BY customer_purchase DESC;

-- How much money each customer has spent

SELECT  
    c.first_name, 
    c.last_name,
    SUM(s.sales_amount) AS amount_spent
FROM gold.dim_customers c
INNER JOIN gold.fact_sales s
ON c.customer_key = s.customer_key
GROUP BY c.customer_key, first_name, last_name
ORDER BY amount_spent DESC;

-- Total of product sold per country

SELECT  
    c.country,
    SUM(s.quantity) AS product_sold_per_country
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales s
ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY product_sold_per_country DESC;
